#!/bin/bash

# Deletes data files and decomposed processor directories for new parallel run 
# Ideal for restarting run with new number of procs
rm -rf 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* log.* processor*
